COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//incubator/api:onos-incubator-api',
    '//apps/routing/common:onos-apps-routing-common',
    '//apps/routing-api:onos-apps-routing-api',
    '//apps/route-service/api:onos-apps-route-service-api',
    '//apps/intentsync:onos-apps-intentsync',
    '//lib:org.apache.karaf.shell.console',
    '//cli:onos-cli'
]

BUNDLES = [
    '//apps/indopronos:onos-apps-indopronos',
    '//apps/routing-api:onos-apps-routing-api',
    '//apps/routing/common:onos-apps-routing-common',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

onos_app (
  app_name = 'org.onosproject.indopronos',
  title = 'indopronos',
  category = 'Traffic Steering',
  url = 'http://onosproject.org',
  included_bundles = BUNDLES,
  description = 'Inter Domain Policy Routing in ONOS',
  required_apps = [
        'org.onosproject.sdnip',
  ],
)
